tap "hashicorp/tap"
tap "pulumi/tap"
# Official Amazon AWS command-line interface
brew "awscli"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Fast and simple Node.js version manager
brew "fnm"
# GitHub command-line tool
brew "gh"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Development kit for the Java programming language
brew "openjdk@21"
# Fast, configurable, shell plugin manager
brew "sheldon"
# Cross-shell prompt for astronauts
brew "starship"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Desktop password and login vault
cask "bitwarden"
# Write, edit, and chat about your code with AI
cask "cursor"
# Databases and SQL IDE
cask "datagrip"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Native desktop client for WhatsApp
cask "whatsapp"
vscode "anthropic.claude-code"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-containers"
vscode "anysphere.remote-ssh"
vscode "astro-build.astro-vscode"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "hashicorp.terraform"
vscode "jannchie.ruff-ignore-explainer"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "naumovs.color-highlight"
vscode "redhat.vscode-yaml"
vscode "vscodevim.vim"
npm "@nestjs/cli"
npm "corepack"
npm "pnpm"
